context:
  version: "26.3.0dev"
  sys_userprofile: ${{ env.get("USERPROFILE", default="") }}
  sys_localappdata: ${{ env.get("LOCALAPPDATA", default="") }}
  sys_appdata: ${{ env.get("APPDATA", default="") }}
  sys_path: ${{ env.get("PATH") }}

package:
  name: pathsim
  version: "${{ version }}"

source:
  - path: ../third_party/FreeCAD
  - path: ../src
    target_directory: src/Mod/CAM/PathSimulator/Dialog

build:
  number: 0
  script:
    - if: win
      then:
        - echo add_subdirectory(App) > src\Mod\CAM\PathSimulator\CMakeLists.txt
        - echo add_subdirectory(Dialog) >> src\Mod\CAM\PathSimulator\CMakeLists.txt
        - python -c "import subprocess, os; env = os.environ.copy(); env['USERPROFILE'] = r'${{ sys_userprofile }}'; env['LOCALAPPDATA'] = r'${{ sys_localappdata }}'; env['APPDATA'] = r'${{ sys_appdata }}'; env['PATH'] = r'${{ sys_path }}'; subprocess.run(['pixi', 'run', 'configure-release'], env=env, check=True)"
        - python -c "import subprocess, os; env = os.environ.copy(); env['USERPROFILE'] = r'${{ sys_userprofile }}'; env['LOCALAPPDATA'] = r'${{ sys_localappdata }}'; env['APPDATA'] = r'${{ sys_appdata }}'; env['PATH'] = r'${{ sys_path }}'; subprocess.run(['pixi', 'run', 'build-release'], env=env, check=True)"
        - mkdir "%PREFIX%\Library\Mod\CAM"
        - copy build\release\Mod\CAM\PathSim.pyd "%PREFIX%\Library\Mod\CAM"
        - copy %RECIPE_DIR%\PathSim.pyi "%PREFIX%\Library\Mod\CAM"
    - if: unix
      then:
        - echo "add_subdirectory(App)" > src/Mod/CAM/PathSimulator/CMakeLists.txt
        - echo "add_subdirectory(Dialog)" >> src/Mod/CAM/PathSimulator/CMakeLists.txt
        - python -c "import subprocess, os; env = os.environ.copy(); env['PATH'] = r'${{ sys_path }}'; subprocess.run(['pixi', 'run', 'configure-release'], env=env, check=True)"
        - python -c "import subprocess, os; env = os.environ.copy(); env['PATH'] = r'${{ sys_path }}'; subprocess.run(['pixi', 'run', 'build-release'], env=env, check=True)"
        - mkdir -p "$PREFIX/Library/Mod/CAM"
        - cp build/release/Mod/CAM/PathSim.so "$PREFIX/Library/Mod/CAM/"
        - cp $RECIPE_DIR/PathSim.pyi "$PREFIX/Library/Mod/CAM/"

requirements:
  run:
    - freecad=1.2.0dev
